version: "3"

services:
  redis-db:
    image: redis:7
    container_name: redis-db
    ports:
      - "6379:6379"
    volumes:
      - ./data:/data
    user: "1000:1000"
    command: ["--save", ""]

    restart: always

  flask-app:
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - redis-db
    container_name: flask-app
    environment:
      - REDIS_HOST=redis-db
      - REDIS_PORT=6379
      - LOG_LEVEL=DEBUG
    ports:
      - "5000:5000"
    volumes:
      - ./src:/code/src
      - ./test:/code/test
    restart: always
  
  worker:
    build: .
    depends_on:
      - redis-db
    command: python worker.py
    restart: always
    environment:
      - REDIS_HOST=redis-db
      - REDIS_PORT=6379
      - LOG_LEVEL=DEBUG
